[workspace]
members = ["cad-cli","cad-geometry", "cad-rest"]
resolver = "3"

[workspace.dependencies]
tokio = { version = "^1.0", features = ["full"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1"
tracing = { version = "0.1" }
