[package]
name = "cad-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
cad-geometry = { path = "../cad-geometry"}
clap = { version = "4", features = ["env", "derive"] }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
