name: Test & Lint

on:
  pull_request:
    branches: ["master"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"

      - name: Rust version
        run: |
          env
          which rustc
          rustc --version

      - name: Check Format
        run: |
          cargo fmt --check

      - name: Check Clippy
        run: |
          cargo clippy --locked -- -Dwarnings

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"

      - name: Rust version
        run: |
          rustup update
          rustup show
          env
          which rustc
          rustc --version

      - name: Test
        run: |
          cargo test
